# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /home/dyang/di/2s-AGCN//data/smarthome/xsub/val_data_joint.npy
  label_path: /home/dyang/di/2s-AGCN//data/smarthome/xsub/val_label.pkl
  debug: False
  random_choose: 4000
  window_size: 400
  normalization: False

# model
model: model.agcn.Model
model_args:
  num_class: 31
  num_point: 15
  num_person: 1
  graph: graph.smarthome.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0,1,2]
test_batch_size: 128
weights: .//runs/smarthome_cs_agcn_joint-59-40020.pt



work_dir: ./work_dir/smarthome/xsub/agcn_test_joint
model_saved_name: ./runs/smarthome_cs_agcn_test_joint
save_score: True

