work_dir: ./work_dir/smarthome/xsub/agcn_joint_1
model_saved_name: ./runs/smarthome_cs_agcn_joint_1
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/dyang/di/2s-AGCN-For-Daily-Living/data/smarthome/xsub/train_data_joint.npy
  label_path: /home/dyang/di/2s-AGCN-For-Daily-Living/data/smarthome/xsub/train_label.pkl
  debug: False
  random_choose: 4000 
  random_shift: False
  random_move: False
  window_size: 400
  normalization: False

test_feeder_args:
  data_path: /home/dyang/di/2s-AGCN-For-Daily-Living/data/smarthome/xsub/val_data_joint.npy
  label_path: /home/dyang/di/2s-AGCN-For-Daily-Living/data/smarthome/xsub/val_label.pkl
  random_choose: 4000
  window_size: 400
  normalization: False

# model
model: model.attention_agcn.Model
model_args:
  num_class: 31
  num_point: 15
  num_person: 1
  graph: graph.smarthome.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0, 1 ,2]
batch_size: 16
test_batch_size: 32
num_epoch: 60
nesterov: True

